### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#1]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## Tests

- [x] The interpreter program executes successfully (mvn exec:java)
- [x] Test cases pass; program prints the fish (mvn test)

## Lox Programming

- [x] Program contains at least 3 Lox language comments

## TODOs

- [x] Program file contains no TODOs
- [x] Reflection contains no TODOs

## Reflection

- [x] Reflection responds to all open-ended, free-response prompts
- [x] Reflection contains adequate number of code fences

## Percent complete

Based on the checks achieved, this assignment is `%` complete.
