### ISSUE TITLE
5 - Evaluating Expressions

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#10]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## Tests

- [x] Divide by zero throws a RuntimeError

- [x] String concatenation works correctly

- [x] String multiplication works correctly

## TODOs

- [x] Interpreter.java contains no TODOs

- [x] Reflection contains no TODOs

## Percent complete

Based on the checks achieved, this assignment is `100%` complete.
