### ISSUE TITLE
6 - Statements and State

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#11]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## Tests

- [x] Programs require variable initialization before use in a program

- [x] The Lox interpreter&#39;s REPL mode works correctly; evaluates expressions and statements

## TODOs

- [x] Interpreter.java contains no TODOs

- [x] Reflection contains no TODOs

## Percent complete

Based on the checks achieved, this assignment is `100%` complete.
