### ISSUE TITLE
7 - Control Flow

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#12]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## Tests

- [x] Break statement ends loop at the correct number (a &#x3D;&#x3D; 7)

- [x] Continue statement bypasses the fourth iteration

- [x] Ternary expression assesses value of a and returns correct branch

## TODOs

- [x] Interpreter.java file contains no TODOs

- [x] Parser.java file contains no TODOs

- [x] Scanner.java file contains no TODOs

- [x] TokenType.java file contains no TODOs

- [x] test.lox file contains no TODOs

- [x] Reflection contains no TODOs

## Percent complete

Based on the checks achieved, this assignment is `100%` complete.
