### ISSUE TITLE
8 - Functions

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#13]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## Tests

- [x] abs() builtin produces the correct value

- [x] pow() builtin produces the correct value

- [x] Interpreter allows anonymous functions as arguments

- [x] Interpreter correctly interprets independent anonymous functions as standalone expressions

- [x] Interpreter throws an error on invalid, non-numeric argument types for abs() and pow()

## TODOs

- [x] Interpreter.java file contains no TODOs

- [x] Parser.java file contains no TODOs

- [x] LoxFunction contains no TODOs

- [x] Expr.java contains updated definitions for function expressions (compile, run GenerateAST)

- [x] Stmt.java contains updated definitions for function statements (compile, run GenerateAST)

- [x] Reflection contains no TODOs

## Percent complete

Based on the checks achieved, this assignment is `100%` complete.
