### ISSUE TITLE
9 - Resolving & Binding

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#14]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## Tests

- [x] Named functions resolve correctly (variable c reported unused)

- [x] Anonymous functions resolve correctly (variable l reported unused)

## Updating Language Features

- [x] Resolver.java contains a definition for visitBreakStatement

- [x] Resolver.java contains a definition for visitConditionalExpr

- [x] Resolver.java resolves function statement bodies as redefined in Stmt.java

- [x] Resolver.java contains a definition for visitFunctionExpr

- [x] Resolver.java resolves function expressions (i.e., anonymous functions) as redefined in Expr.java

## TODOs

- [x] Resolver.java contains no TODOs

- [x] Reflection contains no TODOs

## Percent complete

Based on the checks achieved, this assignment is `100%` complete.
