### ISSUE TITLE
10 - Classes

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#15]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## TODOs

- [x] TokenType.java contains no TODOs

- [x] Scanner.java contains no TODOs

- [x] Parser.java contains no TODOs

- [x] LoxFunction.java contains no TODOs

- [x] Resolver.java contains no TODOs

- [x] Interpreter.java contains no TODOs

- [x] Reflection contains no TODOs

## import statements

- [x] TokenType.java contains the IMPORT token definition

- [x] Scanner.java defines IMPORT as a keyword

- [x] Parser.java calls separate declaration for imports if matching IMPORT keyword

## Tests

- [x] Program produces correct output, accounting for &#39;getters&#39; and imports

- [x] test.lox program is unedited

- [x] fish.lox program is unedited

## Percent complete

Based on the checks achieved, this assignment is `100%` complete.
