### ISSUE TITLE
2 - Scanning

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#4]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## Tests

- [x] The interpreter program executes successfully (mvn exec:java)

- [x] Test cases pass; program handles multi-line comments without breaking other functionality (mvn test)

## Lox Programming

- [x] Program contains at least 1 Lox multi-line comment

## TODOs

- [x] Program file contains no TODOs

- [x] Reflection contains no TODOs

## Reflection

- [x] Reflection responds to all open-ended, free-response prompts

- [x] Reflection contains adequate number of code fences

## Percent complete

Based on the checks achieved, this assignment is `100%` complete.
