### ISSUE TITLE
3 - Representing Code

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#7]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## Tests

- [x] The interpreter program executes successfully (mvn exec:java)

- [x] Test cases pass; both AST and RPN representations are correct

## TODOs

- [x] test.lox program contains no TODOs

- [x] Reflection contains no TODOs

- [x] ASTPrinter.java contains no TODOs

## Reflection

- [x] Reflection contains adequate number of code fences

## AST

- [x] Expr.java file exists (AST generated)

- [x] ASTPrinter.java implements RPN without using System.out.println

## Percent complete

Based on the checks achieved, this assignment is `100%` complete.
