### ISSUE TITLE
4 - Parsing Expressions

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox#9]
# `TODO`s

The latest run of the GatorGrader on this assignment shows you've finished all the tasks!

## Tests

- [x] The interpreter program executes successfully (mvn exec:java)

- [x] Comma expression production rule functions correctly

- [x] Ternary expression production rule functions correctly

## TODOs

- [x] Parser.java contains no TODOs

- [x] TokenType.java contains no TODOs

- [x] ASTPrinter.java contains no TODOs

- [x] Reflection contains no TODOs

## Percent complete

Based on the checks achieved, this assignment is `100%` complete.
